version: '2'
services:
  db:
    image: mafs/oracledb:web_ca-db
    ports:
      - 1521:1521

  oracle_ecto:
    build: .
    volumes:
      - ${WORKSPACE}/oracle_ecto/:/app
      - ${WORKSPACE}/oracleex/:/oracleex
    depends_on:
      - db
