version: '3'
services:
  # db:
  #   image: mafs/oracledb:web_ca-db
  #   ports:
  #     - 1521:1521

  db:
    image: mafs/oracledb:web_ca-19.3.0-se2
    ports:
      - 1521:1521

  oracle_ecto:
    build:
      context: .
      dockerfile: Dockerfile
    image: mafs/oracle_ecto:oralce-19c
    volumes:
      - ${WORKSPACE}/oracle_ecto/:/app
    depends_on:
      - db
