version: '3'
services:
  db:
    image: mafs/oracledb:web_ca-db
    ports:
      - 1521:1521

  oracle_ecto:
    build:
      context: .
      dockerfile: Dockerfile.19c
    image: mafs/oracle_ecto:oralce-19c
    volumes:
      - ${WORKSPACE}/oracle_ecto/:/app
      - ${WORKSPACE}/oracleex/:/oracleex
    depends_on:
      - db
